export enum APP_ICONS {
  CART_ICON = "CART_ICON",
  FILTER_ICON = "FILTER_ICON",
  HOME_ICON = "HOME_ICON",
  SEARCH_ICON = "SEARCH_ICON",
  USER_ICON = "USER_ICON",
  SHIPPING_ICON = "SHIPPING_ICON",
  MINUS_ICON = "MINUS_ICON",
  PLUS_ICON = "PLUS_ICON",
}

export enum ERROR_TYPE {
  SERVER = "SERVER",
  APOLLO = "APPOLO",
}
